name: Spellcheck Excel File

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'File name for spellcheck'
        required: true

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install hanspell openpyxl

      - name: Run spellcheck
        run: python spellcheck.py

      - name: Save results
        run: |
          cp output.html ./output/output.html

      - name: Upload results to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
